### ISSUE TITLE
404 exceptions are not getting caught after upgrade

### ISSUE THREAD

**Issue by kumar303** [mozilla/solitude#420]
After the Django upgrade (https://github.com/mozilla/solitude/pull/415) I'm getting this locally (a 500) instead of a 404. I'm going to try and dig in, just posting it here for safe keeping:

````
[18/May/2015 13:59:27]"GET /generic/buyer/?uuid=fxa%3Af39ab5ce102945a692c08d429a87fbfb HTTP/1.1" 200 374
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rest_framework/views.py", line 399, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rest_framework/views.py", line 396, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rest_framework/decorators.py", line 49, in handler
    return func(*args, **kwargs)
  File "/srv/solitude/lib/brains/views/token.py", line 9, in generate
    return Response({'token': get_client().ClientToken.generate()})
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/braintree/client_token.py", line 25, in generate
    return gateway.generate(params)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/braintree/client_token_gateway.py", line 17, in generate
    response = self.config.http().post("/client_token", params)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/braintree/util/http.py", line 49, in post
    return self.__http_do("POST", path, params)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/braintree/util/http.py", line 74, in __http_do
    Http.raise_exception_from_status(status)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/braintree/util/http.py", line 34, in raise_exception_from_status
    raise NotFoundError()
NotFoundError
````

**Comment by andymckay** [comment]
Do you have the BRAINTREE_MERCHANT_ID correctly configured? I noticed that if it's set to an empty string, you get back a NotFoundError.

The correct answer here would be to ensure BRAINTREE_MERCHANT_ID is set in the get_client() call.

```
In [1]: from django.conf import settings

In [2]: settings.BRAINTREE_MERCHANT_ID
Out[2]: ''

In [4]: from lib.brains.client import get_client

In [5]: get_client().ClientToken.generate()
---------------------------------------------------------------------------
NotFoundError
```
vs 
```
In [1]: from django.conf import settings

In [2]: settings.BRAINTREE_MERCHANT_ID
Out[2]: 'tbb...'

In [3]: from lib.brains.client import get_client

In [4]: get_client().ClientToken.generate()
Out[4]: u'eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0 
```

**Comment by kumar303** [comment]
yep, that was the problem. This should fix it https://github.com/mozilla/solitude/pull/415
